# Generated by Django 5.0.6 on 2024-05-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='comment',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='lastname',
        ),
    ]
