# Generated by Django 5.0.6 on 2024-05-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_aboutcontacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontacts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Изображение страницы'),
        ),
    ]
