# Generated by Django 5.0.6 on 2024-05-23 16:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_aboutcontacts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontacts',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
