# Generated by Django 5.0.6 on 2024-05-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo/', verbose_name='Фото сотрудника')),
                ('fullname', models.CharField(max_length=255, verbose_name='ФИО')),
                ('profession', models.CharField(max_length=255, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
