# Generated by Django 5.0.6 on 2024-05-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название страницы')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изображение страницы')),
            ],
            options={
                'verbose_name': 'О галереи',
                'verbose_name_plural': 'О галереях',
            },
        ),
    ]
