# Generated by Django 5.0.6 on 2024-05-23 04:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_alter_news_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='desc2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
