# Generated by Django 5.0.6 on 2024-05-23 05:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0007_news_desc2'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
    ]
