# Generated by Django 5.0.6 on 2024-05-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_news_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название страницы')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изображение страницы')),
            ],
            options={
                'verbose_name': 'О Команде',
                'verbose_name_plural': 'О Командах',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutgallery',
            options={'verbose_name': 'О Галереи', 'verbose_name_plural': 'О Галереях'},
        ),
    ]
