# Generated by Django 5.0.6 on 2024-05-23 17:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_aboutband_alter_aboutgallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutband',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='aboutband',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Изображение страницы'),
        ),
    ]
