# Generated by Django 5.0.6 on 2024-05-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='insta',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='pinterest',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='title',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='twitter',
        ),
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Логотип'),
            preserve_default=False,
        ),
    ]
