# Generated by Django 5.0.6 on 2024-05-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='image2',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagram',
            name='image3',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagram',
            name='image4',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagram',
            name='image5',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagram',
            name='image6',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagram',
            name='image7',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagram',
            name='image8',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagram',
            name='image9',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
