# Generated by Django 5.0.6 on 2024-05-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_instagram_image2_instagram_image3_instagram_image4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='image2',
            field=models.ImageField(upload_to='image/', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='image3',
            field=models.ImageField(upload_to='image/', verbose_name='Изображение 3'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='image4',
            field=models.ImageField(upload_to='image/', verbose_name='Изображение 4'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='image5',
            field=models.ImageField(upload_to='image/', verbose_name='Изображение 5'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='image6',
            field=models.ImageField(upload_to='image/', verbose_name='Изображение 6'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='image7',
            field=models.ImageField(upload_to='image/', verbose_name='Изображение 7'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='image8',
            field=models.ImageField(upload_to='image/', verbose_name='Изображение 8'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='image9',
            field=models.ImageField(upload_to='image/', verbose_name='Изображение 9'),
        ),
    ]
