# Generated by Django 5.0.6 on 2024-05-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_settings_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='address',
        ),
    ]
