# Generated by Django 5.0.6 on 2024-05-18 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_settings_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='logo',
        ),
    ]
