# Generated by Django 5.0.6 on 2024-05-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_whychooseus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatDoWeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Что мы предлагаем',
                'verbose_name_plural': 'Что мы предлагаем',
            },
        ),
    ]
