# Generated by Django 5.0.6 on 2024-05-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_whatdoweoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('subdesc', models.TextField(verbose_name='Подописание')),
            ],
            options={
                'verbose_name': 'Почему выбирает нас',
                'verbose_name_plural': 'Почему выбирают нас',
            },
        ),
    ]
