# Generated by Django 5.0.6 on 2024-05-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
    ]
