# Generated by Django 5.0.6 on 2024-05-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='image/', verbose_name='Логотип комментатора')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('name', models.CharField(max_length=100, verbose_name='Имя комментатора')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
