# Generated by Django 5.0.6 on 2024-05-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_whatdoweofferimage_whychooseusimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='insta',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='pinterest',
            field=models.URLField(blank=True, null=True, verbose_name='Pinterest'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
    ]
