# Generated by Django 5.0.6 on 2024-05-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_settings_facebook_alter_settings_insta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название страницы')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Изображение страницы')),
            ],
            options={
                'verbose_name': 'Об о нас',
                'verbose_name_plural': 'Об о нас',
            },
        ),
    ]
