# Generated by Django 5.0.6 on 2024-05-23 16:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_aboutabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutabout',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
