# Generated by Django 5.0.6 on 2024-05-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_aboutabout_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='email_link',
            field=models.URLField(default=1, verbose_name='Ссылка для почты'),
            preserve_default=False,
        ),
    ]
