# Generated by Django 5.0.6 on 2024-05-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_settings_email_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='logo',
        ),
        migrations.AddField(
            model_name='comments',
            name='image',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
