# Generated by Django 5.0.6 on 2024-05-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_comments_options_remove_comments_logo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='settings',
            name='image',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
